// Networking email provider abstraction — provider-agnostic.
// Mirrors the registry pattern used by jobs-api.ts and notifications.ts.
//
// No provider is connected yet. The UI must never claim a message was "sent"
// unless a registered provider's send() resolves successfully. Drafts are
// generated by the AI service layer (networking.ts) but delivery is gated here.
//
// Future adapters (Gmail, Outlook, LinkedIn DMs, a CRM) implement
// NetworkEmailProvider and register via registerNetworkEmailProvider().

export interface NetworkEmailSendRequest {
  to: string;
  subject: string;
  body: string;
  // Optional provider-specific metadata (thread id, reply-to, etc.)
  meta?: Record<string, string>;
}

export interface NetworkEmailSendResponse {
  provider: string;
  messageId: string;
  sentAt: string;
}

export interface NetworkEmailProvider {
  readonly name: string;
  send(req: NetworkEmailSendRequest): Promise<NetworkEmailSendResponse>;
}

const providers: Record<string, NetworkEmailProvider> = {};

export function registerNetworkEmailProvider(name: string, provider: NetworkEmailProvider) {
  providers[name] = provider;
}

export function getActiveNetworkEmailProviderName(): string | null {
  const configured = process.env.NETWORK_EMAIL_PROVIDER;
  if (configured && providers[configured]) return configured;
  return Object.keys(providers).length > 0 ? Object.keys(providers)[0] : null;
}

export function getNetworkEmailProvider(): NetworkEmailProvider | null {
  const name = getActiveNetworkEmailProviderName();
  if (!name) return null;
  return providers[name];
}

export function isNetworkEmailConfigured(): boolean {
  return getActiveNetworkEmailProviderName() !== null;
}
